spring:
  datasource:
    name: task_manager
    url: jdbc:postgresql://localhost:5432/informacoes_nutricionais
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
